---
ansible_user: deploy
ansible_ssh_pass: password
ansible_sudo_pass: password

internal_base_domain: ists.io
dmz_base_domain: cybertigers.club

# Certs #
cert_country: Hackistan
cert_state: Hacktavia
cert_local: Hacktopolis
cert_org: RITSEC-BLUE
cert_full_subj: "/C={{ cert_country }}/ST={{ cert_state }}/L={{ cert_local }}/O={{ cert_org }}/CN={{ inventory_hostname }}"