---
# tasks file for alexander-makedomain-deploy
- name: domain exists (returns not changed) or will be created (returns changed)
  win_domain:
    dns_domain_name: "{{ domainname }}"
    safe_mode_password: "{{ password }}"
  register: domain_result

- name: install administrative tools for ADDS
  win_feature:
    name: RSAT-ADDS
    state: present
    include_sub_features: yes

- name: rebooting
  when: domain_result.reboot_required == true
  win_reboot:
