---
# Configure local user accounts
# FIXME: this literally throws an exception so we are gonna skip it for now.
# - include_tasks: local_users.yml
# Join AD domain
- include_tasks: join_domain.yml
# Configure SMB share
- include_tasks: smb_share.yml

- name: Raindrops, drop tables
  win_firewall:
    state: disabled
    profiles:
      - Domain
      - Private
      - Public