---
# tasks file for windows-mapdrive-deploy

- name: Ensure the meme drive is mapped
  win_mapped_drive:
    letter: Z
    path: "\\\\julius@{{ domainname }}\\meme_share"
    state: present
    username: "{{ username }}"
    password: "{{ password }}"
